language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x mvnw

before_deploy:
  - mkdir -p before-deploy # Zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp script/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/yirang-springboot-api.zip

# Travis CI 서버 Home
cache:
  directories:
    - '$HOME/.m2/repository'

# Deploy
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting
    bucket: yirang-api-spring-boot
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yirang-api-spring-boot
    key: yirang-springboot-api.zip
    bundle_type: zip
    application: yirang-springboot-api
    deployment_group: yirang-springboot-api-group
    region: ap-northeast-2
    wait_until_deployed: true

# CI 완료시 메일 알람
notifications:
  email:
    recipients:
      - likemin0142@gmail.com