GET http://localhost:8080/v1/apis/seniors/area?region=달서구
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9oQTFWdS9idHFGS1h4ZlFzWC95MGhIalpsNlhaVWVScFdPa3lrTGtLL2ltZ182NDB4NjQwLmpwZyIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2MDUzNjgxMzIsImV4cCI6MTYwNTQ1NDUzMn0.ULpJtR0vTw-pksmMCYuZHBiSc4h9YDVzLFJypZoJswE
##########

GET http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/seniors/myArea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuKZoeyXsOuJtOungeKZoSIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9icVYzaDQvYnRxSHdnOU05aDIvSDcxVjRUbzQ3N0VLa3pzNFVMaTd6Sy9pbWdfNjQweDY0MC5qcGciLCJ1c2VySWQiOiIxNDY2MzU5MzU3Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjA4NTI5MzM4LCJleHAiOjE2MDg2MTU3Mzh9.U_00A-IJbec6oP-QxgLKibhusFA4i725bF62Au2bWjE