PUT http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/admins/1468416139
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNDY4NDE2MTM5IiwiaWF0IjoxNjE3Mjc1OTU4LCJleHAiOjE2MTczNjIzNTh9.Z-pV-Ww5pZhoblFxP1hPez4PmwrYH8jr__epJytj2Tg
Content-Type: application/json

{
 "regions": ['중구', '서구', '남구']
}
########
GET http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/admins/user-auths
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9oQTFWdS9idHFGS1h4ZlFzWC95MGhIalpsNlhaVWVScFdPa3lrTGtLL2ltZ182NDB4NjQwLmpwZyIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE2MTM0NzIxNDUsImV4cCI6MTYxMzU1ODU0NX0.4h_oM0YXjy6fUzIjSnSroeGj2WGady7iXboWBaITshQ
