POST http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/admins
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuyaqeybkCIsImltZ1VybCI6InVua25vd24iLCJ1c2VySWQiOiIxNDY2MzE1NDkxIiwicm9sZSI6IlZPTFVOVEVFUiIsImlhdCI6MTYxMTIzNDYyNywiZXhwIjoxNjExMzIxMDI3fQ.Gxl0fyAIjtFkpEOBPekfaOY89cETebM5rJy2KS1N0_I
###

DELETE http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/admins
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9oQTFWdS9idHFGS1h4ZlFzWC95MGhIalpsNlhaVWVScFdPa3lrTGtLL2ltZ182NDB4NjQwLmpwZyIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJyb2xlIjoiVk9MVU5URUVSIiwiaWF0IjoxNjAzOTYwMTMzLCJleHAiOjE2MDQwNDY1MzN9.PyGnYsaPDHrEAmudxPkifiJeWYFvsTT1szWlLouMHZw
###

