POST http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/admins/region/중구
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuyxhOydgCIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9tejhiaS9idHFHSHE1QkxnMC84cU5aTjROYWQzZ1hrb1h1b0paNUoxL2ltZ182NDB4NjQwLmpwZyIsInVzZXJJZCI6IjE0NzAzOTEzOTQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2MTAzNDUzNDAsImV4cCI6MTYxMDQzMTc0MH0.ZkmD6vWqX1dq_i1i8ZX964WC7U6-304gWEZzQbikia4
