POST http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/admins/region/달성군
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuyaqeybkCIsImltZ1VybCI6InVua25vd24iLCJ1c2VySWQiOiIxNDY2MzE1NDkxIiwicm9sZSI6IlNVUEVSX0FETUlOIiwiaWF0IjoxNjExMjM0ODE3LCJleHAiOjE2MTEzMjEyMTd9.Q7AnrSMz-LASERgHpZwF8xMhvRhkmGlh9GHODEhxvkY
########
GET http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/admins/user-auths
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9oQTFWdS9idHFGS1h4ZlFzWC95MGhIalpsNlhaVWVScFdPa3lrTGtLL2ltZ182NDB4NjQwLmpwZyIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE2MTM0NzIxNDUsImV4cCI6MTYxMzU1ODU0NX0.4h_oM0YXjy6fUzIjSnSroeGj2WGady7iXboWBaITshQ
