POST http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/admins/region/동구
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuKZoeyXsOuJtOungeKZoSIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9icVYzaDQvYnRxSHdnOU05aDIvSDcxVjRUbzQ3N0VLa3pzNFVMaTd6Sy9pbWdfNjQweDY0MC5qcGciLCJ1c2VySWQiOiIxNDY2MzU5MzU3Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjA0OTA0NTU3LCJleHAiOjE2MDQ5OTA5NTd9.ZpITYp-uLtiKaX0T7fQdQoIiIDV1fKg2TK7ZRONv3Ro
###
DELETE http://localhost:8080/v1/apis/admins/region/중구
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2MDM5NzE4MDUsImV4cCI6MTYwNDA1ODIwNX0.-Dag0IiPEDFXeqRI7zfP29xu2dw-tgS2JA-AcCf0goA
###
GET http://localhost:8080/v1/apis/admins/region
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2MDM5NzE4MDUsImV4cCI6MTYwNDA1ODIwNX0.-Dag0IiPEDFXeqRI7zfP29xu2dw-tgS2JA-AcCf0goA