POST http://localhost:8080/v1/apis/auth/signin
Content-Type: application/json

{
 "accessToken": "DF0yPRBKl3nyRs-OS19-B0E_xyqocQb5PBTtTwopyV4AAAF0fNprWQ",
  "refreshToken": "Refresh",
  "refreshTokenExpiredTime": 1000
}
