POST http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/auth/signin
Content-Type: application/json

{
 "accessToken": "Dac-TWpNF1tHpPK5qEjruWvsVFdv1kDwtD1nOwopcBQAAAF0dpm7FA",
  "refreshToken": "Refresh",
  "refreshTokenExpiredTime": 1000
}