POST http://localhost:8080/v1/apis/auth/signin
Content-Type: application/json

{
 "accessToken": "LboVsNsQ8Zr4KSuSq_OWiWevabmArYZ2RPMUjAo9dZsAAAF0c4wmog",
  "refreshToken": "Refresh",
  "refreshTokenExpiredTime": 1000
}
