POST http://localhost:8080/v1/apis/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsImltZ1VybCI6IuycoOygleuvvCIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJyb2xlIjoiVk9MVU5URUVSIiwiaWF0IjoxNjAzMzgyOTI1LCJleHAiOjE2MDM0NjkzMjV9.nwaMWJP9TwLXWf_Ant_oDD3AopFJzzSyC2DFXQ3zCj0