POST http://localhost:8080/v1/apis/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNDY2MzE1NDkxIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE1OTk4MjI1NjIsImV4cCI6MTU5OTkwODk2Mn0.2wpYa--H4Eh6zPQ3waE3uvyXnRC7HXcENq1OFbCYlkA