POST http://localhost:8080/v1/apis/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNDY2MzE1NDkxIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE1OTk4MTM3NzAsImV4cCI6MTU5OTkwMDE3MH0.BtG1WDIejcZ0WFA1xmOvZb1n3N2Dq8DDABBR_k8Mwbo