POST http://localhost:8080/v1/apis/auth/signin
Content-Type: application/json

{
 "accessToken": "FkcUtiChT109CrtxV69XVL4BbXjY8yrj7Qt4nQo9dNoAAAF4IOLC6Q",
 "refreshToken": "Refresh",
  "refreshTokenExpiredTime": 1000
}
###

###
POST http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/auth/signin
Content-Type: application/json

{
 "accessToken": "1vWrpK2_p_b3OmTFQaDX2AB6WtjDfAAVEs4SJgo9dJcAAAF0ltPHOg",
  "refreshToken": "Refresh",
  "refreshTokenExpiredTime": 1000
}

###
POST http://localhost:8080/v1/apis/auth/fake/signin
Content-Type: application/json

{
 "fakeAuthority": "volunteer_4"

}


