### 이메일 주소 바꾸기
PUT http://localhost:8080/v1/apis/emails
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9oQTFWdS9idHFGS1h4ZlFzWC95MGhIalpsNlhaVWVScFdPa3lrTGtLL2ltZ182NDB4NjQwLmpwZyIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJlbWFpbCI6Imxpa2VtaW4wMTQyQG5hdmVyLmNvbSIsImlhdCI6MTYxNDE3ODk4NCwiZXhwIjoxNjE0MjY1Mzg0fQ.rFkyasOyt2ul3ttKovF89ztjlT_HnriLrnUEVe2Mz7I

{
 "email": "likemin5517@naver.com"
}
### 자신의 이메일이 검증 되었는지 확인
GET http://localhost:8080/v1/apis/emails
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9oQTFWdS9idHFGS1h4ZlFzWC95MGhIalpsNlhaVWVScFdPa3lrTGtLL2ltZ182NDB4NjQwLmpwZyIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJlbWFpbCI6Imxpa2VtaW4wMTQyQG5hdmVyLmNvbSIsImlhdCI6MTYxNDE3ODk4NCwiZXhwIjoxNjE0MjY1Mzg0fQ.rFkyasOyt2ul3ttKovF89ztjlT_HnriLrnUEVe2Mz7I

### 자신의 이메일 인증번호 생성 (localhost)
POST http://localhost:8080/v1/apis/emails/certification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIzMzI4NiIsImlhdCI6MTYxNjQ3MDIyNywiZXhwIjoxNjE2NTU2NjI3fQ.5X_VfIgIIbuu9LBC0MR7sFChEOqRcp0Mc7ZGs9zXUBU

### 자신의 이메일 인증번호 생성 (실서버)
POST http://ec2-3-35-99-114.ap-northeast-2.compute.amazonaws.com:8080/v1/apis/emails/certification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNDY4NDE2MTM5IiwiaWF0IjoxNjE2NDcwMzY2LCJleHAiOjE2MTY1NTY3NjZ9.NWIfZopj5XaFlnrNqETOFNdq1C6jCENTgqeH0jLr8IU

### 이메일 인증으로 확인
POST http://localhost:8080/v1/apis/emails/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IuycoOygleuvvCIsImltZ1VybCI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9oQTFWdS9idHFGS1h4ZlFzWC95MGhIalpsNlhaVWVScFdPa3lrTGtLL2ltZ182NDB4NjQwLmpwZyIsInVzZXJJZCI6IjE0Njg0MTYxMzkiLCJlbWFpbCI6Imxpa2VtaW4wMTQyQG5hdmVyLmNvbSIsImlhdCI6MTYxNDE3ODk4NCwiZXhwIjoxNjE0MjY1Mzg0fQ.rFkyasOyt2ul3ttKovF89ztjlT_HnriLrnUEVe2Mz7I

{
 "certificationNumbers": 388645
}